"""Defines a custom AiiDA node visualiser."""

import aiidalab_widgets_base as awb
import ipywidgets as ipw
from aiida.common.links import LinkType
from aiida.orm import ArrayData, Node, ProcessNode
from alc_aiidalab_widgets.viewers import ALC_AIIDA_VIEWER_MAPPING
from IPython.display import clear_output, display
from traitlets import Instance, observe


class CustomAiidaNodeViewWidget(ipw.VBox):
    """
    Custom viewer based on a specific AiiDA node type.

    An extension of the aiida_widgets_base.viewers.AiidaNodeViewWidget
    enabling more customisability when registering viewers with nodes
    returned from ChemShell jobs. The main outline is taken from the base
    aiidalab_widgets_base viewer with an extended viewer() method which
    allows handling of node types which the base viewer has no registered
    visualisation widgets.
    """

    node = Instance(Node, allow_none=True)

    def __init__(self, **kwargs):
        """CustomAiidaNodeViewWidget Constructor."""
        self._output = ipw.Output()
        self.node_views = {}
        self.node_view_loading_message = awb.loaders.LoadingWidget("Loading Node View")
        super().__init__(**kwargs)
        self.add_class("aiida-node-view-widget")

    @observe("node")
    def _observe_node(self, change):
        if not ((node := change["new"]) and node != change["old"]):
            return
        if node.uuid in self.node_views:
            self.children = [self.node_views[node.uuid]]
            return
        self.children = [self.node_view_loading_message]
        node_view = self._viewer(node)
        if isinstance(node_view, ipw.DOMWidget):
            self.node_views[node.uuid] = node_view
            self.children = [node_view]
        else:
            with self._output:
                clear_output()
                if change["new"]:
                    display(node_view)
            self.children = [self._output]

    def _viewer(self, node: Node, **kwargs):  # noqa: C901
        """Create a viewer based on the type of Node being visualised."""
        # First look for ALC developed node viewers
        _viewer = ALC_AIIDA_VIEWER_MAPPING.get(node.node_type)
        if not _viewer:
            # Fall back to default AiiDAlab developed node viewers
            _viewer = awb.viewers.AIIDA_VIEWER_MAPPING.get(node.node_type)
        if isinstance(node, ProcessNode):
            # Allow to register specific viewers based on node.process_type
            _viewer = ALC_AIIDA_VIEWER_MAPPING.get(node.process_type, _viewer)  # type: ignore
            if not _viewer:
                _viewer = awb.viewers.AIIDA_VIEWER_MAPPING.get(
                    node.process_type, _viewer
                )

        # Handle ChemShell specific output nodes
        incoming_links = node.get_incoming(link_type=LinkType.CREATE).all()
        if incoming_links:
            # If there's only one creator (typical for CalcJob outputs):
            link = incoming_links[0]

            # Check that the node was generated by ChemShell
            # print(link.source.process_type)
            if link.node.process_type and "chemshell" in link.node.process_type:
                link_name = link.link_label
                # parent_node = link.source  # This is your CalcJobNode object
                if link_name == "optimised_structure":
                    _viewer = ALC_AIIDA_VIEWER_MAPPING.get(
                        "data.core.structure.StructureData.", _viewer
                    )
                elif link_name == "vibrational_modes":
                    _viewer = VibrationalModesViewWidget
                elif link_name == "gradients":
                    _viewer = ALC_AIIDA_VIEWER_MAPPING.get("xyz_table", _viewer)
                elif link_name in ["energy", "final_energy"]:
                    return f"Final SCF Energy (Hartree): {node.value}"

        if _viewer:
            return _viewer(node, **kwargs)
        # No viewer registered for this type, return node itself
        return node


class VibrationalModesViewWidget(ipw.VBox):
    """Custom widget to display vibrational modes produced from ChemShell."""

    def __init__(self, array: ArrayData, **kwargs):
        """VibrationalModesViewWidget Constructor.

        Parameters
        ----------
        array : ArrayData
            The AiiDA ArrayData object to display.
        """
        super().__init__(**kwargs)
        self.array = array
        values = self.array.get_array("Modes")
        # Construct HTML Table
        html = "<table style='width:100%; border: 1px solid #ddd; text-align: left; "
        html += "border-collapse: collapse;'>"
        html += "<tr style='background-color: #2196F3; color: white;'>"
        html += "<th>Mode</th><th>Frequency</th><th>Vib T / K</th><th>ZPE / H</th>"
        html += "</th><th>Energy / H</th></th><th>-TS / H</th></tr>"

        for idx, row in enumerate(values):
            bg_color = "#f9f9f9" if idx % 2 == 0 else "#ffffff"
            html += f"<tr style='background-color: {bg_color};'>"
            html += f"<td><b>{idx}</b></td><td>{row[0]:.6f}</td><td>{row[1]:.6f}</td>"
            html += f"<td>{row[2]:.6f}</td><td>{row[3]:.6f}</td><td>{row[4]:.6f}</td>"
            html += "</tr>"
        html += "</table>"

        self.children = [ipw.HTML(html)]

        return
